name: Deploy Docker Image

on: workflow_dispatch

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3
         - name: Setup node
           uses: actions/setup-node@v3
           with:
              node-version: '18'
         - name: Install dependencies
           run: npm ci
         - name: Lint
           run: npm run lint
         - name: Generate image version
           run: "::set-output name=docker-image-version::$(date +%s)"
           id: version
         - name: Build the Docker image
           run: docker build . -t roman20003821/node-js-on-docker:${{ steps.version.docker-image-version }}
         - name: Publish the image to Docker Hub
           run: docker push roman20003821/node-js-on-docker:${{ steps.version.docker-image-version }}
